### ISSUE TITLE
쭈원이슈 - 방어회에 관한 인사이트

### ISSUE THREAD

**Issue by hanaluana** [hanaluana/collabo#1]
# 방어회 맛있게 먹고 오겠습니다
1. 2호선
2. **홍대입구역** 하차
3. 연남동 걸어가기
4. **방어** 우겨넣기 우걱우걱

**Comment by zooo1** [comment]
슨상님,, 방어회는 김에 싸먹는 것이 맛있읍니다 ,,

**Comment by hanaluana** [comment]
![bbbb](https://user-images.githubusercontent.com/41250764/50746154-1d148800-1271-11e9-8b83-febccc6e7ef7.jpg)
This is 영롱

**Comment by zooo1** [comment]
내일 꼭 리뷰해주기,,, <3

**Comment by hanaluana** [comment]
이제 그만 방어는 닫아버리자꾸나..
Say 굿바이....
